general {
    layout=dwindle
    allow_tearing = 0
    gaps_in = 2
    gaps_out = 6
    border_size = 2
    col.active_border = rgba(0DB7D4FF) rgba(7AA2F7FF) rgba(9778D0FF) 45deg
    col.inactive_border = rgba(04404aaa)
}

xwayland {
    use_nearest_neighbor = 0
    force_zero_scaling = 1
    create_abstract_socket = 1
}

input {
    #kb_layout=gb
    repeat_rate=50
    repeat_delay=300
    numlock_by_default=1
    left_handed=0

    follow_mouse=2
    accel_profile=flat
}

animations {
    enabled = yes

    bezier = windowIn, 0.06, 0.71, 0.25, 1
    bezier = windowResize, 0.04, 0.67, 0.38, 1

    animation = windowsIn, 1, 1, windowIn, slide #popin 20%
    animation = windowsOut, 1, 1, windowIn, slide #popin 70%
    animation = windowsMove, 1, 0.75, windowResize
    animation = border, 1, 10, default
    animation = borderangle, 1, 50, default, loop
    animation = fade, 1, 1, default
    animation = workspaces, 1, 1, default
}

dwindle {
    preserve_split = 1
}

render {
    direct_scanout = false
}

opengl {
    nvidia_anti_flicker = 0
}

cursor {
    no_hardware_cursors = 0
    enable_hyprcursor = 1
    use_cpu_buffer = 0
    sync_gsettings_theme = 1
}

decoration {
    rounding=32
    rounding_power=1.15
    active_opacity = 1.0
    inactive_opacity = 0.88
    blur {
        enabled = true
        xray = false
        size = 2
        passes = 3
        new_optimizations = on
        
        noise = 0.01
        contrast = 1.6
        brightness = 1.1
    }
    shadow {
        enabled = true
        range = 16
        render_power = 3
        offset = 0 0
        color = rgba(0f0f1a44)
        color_inactive = rgba(00000022)
    }
}

misc {
    vrr = 2
    disable_hyprland_guiutils_check = true
    enable_swallow = false
    swallow_regex = ^(kitty)$
    disable_hyprland_logo = true
    disable_splash_rendering = true
    focus_on_activate = true
    animate_manual_resizes = true
    animate_mouse_windowdragging = true
    mouse_move_enables_dpms = true
    key_press_enables_dpms = true
    middle_click_paste = false
}

debug {
    overlay = 0
    damage_blink = 0
    damage_tracking = 2
}

source=~/.config/hypr/env.conf
source=~/.config/hypr/exec.conf
source=~/.config/hypr/keybinds.conf
source=~/.config/hypr/monitors.conf
source=~/.config/hypr/windows.conf
exec-once = python3 "/home/sarath/projects/pikaHyprland/mpv_bridge.py"
bind = $mainMod, S, exec, curl -s http://127.0.0.1:9999/api/link_audio
bind = $mainMod, M, exec, curl -s http://127.0.0.1:9999/api/toggle_mic
bind = $mainMod, K, exec, curl -s http://127.0.0.1:9999/api/vol_up
bind = $mainMod, J, exec, curl -s http://127.0.0.1:9999/api/vol_down
